### ISSUE TITLE
Time Range for ATLAS forced photometry button

### ISSUE THREAD

**Issue by dsand** [SAGUARO-MMA/kne-cand-vetting#18] opened 2024-04-07 14:59 UTC
I have noticed that running the ATLAS forced photometry button can be time consuming and can make the web site unresponsive.  I think this is because we are trying to run forced photometry for hundreds of days by default.

Should we have multiple buttons or options?  Maybe the default should be to run ATLAS forced photometry on the last two weeks, and then perhaps another button that does the full year (or whatever the current button does).  I do think having both options is important.

**Comment by griffin-h** [comment] 2024-04-07 16:03
I think this is mostly a duplicate of SAGUARO-MMA/saguaro_tom#62. Can you consolidate the suggestions there? In terms of this repo, I already added variable time options in #13.

**Closed by griffin-h** 2024-04-07 16:03 UTC

**Comment by dsand** [comment] 2024-04-07 16:07
Yikes.  History is repeating itself.  We should probably go back and look at some of our stale issues.
